src/FixMyHouse/Models/ArtisanViewModel.cs
namespace FixMyHouse.Models;

public record ArtisanViewModel(
    Guid Id,
    string FirstName,
    string FullName,
    string Bio,
    string Picture,
    IReadOnlyList<ArtisanServiceViewModel> Services
);

src/FixMyHouse/Controllers/ArtisansController.cs
using FixMyHouse.Data;
using FixMyHouse.Models;
using FixMyHouse.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FixMyHouse.Controllers;

public sealed class ArtisansController : Controller
{
    private readonly ApplicationDbContext _db;

    public ArtisansController(ApplicationDbContext db)
    {
        _db = db ?? throw new ArgumentNullException(nameof(db));
    }

    public async Task<IActionResult> List()
    {
        var entities = await _db.Artisans.AsNoTracking().ToListAsync();
        var models = entities.Select(static x => x.ToViewModel()).ToList();
        return View(models);
    }

    [Route("[controller]/{id:guid}")]
    public async Task<IActionResult> View(Guid id)
    {
        var entity = await
            _db.Artisans
            .AsNoTracking()
            .Include(x => x.Services!).ThenInclude(x => x.Service)
            .SingleOrDefaultAsync(x => x.Id == id);

        if (entity is null) { return NotFound(); }
        var model = entity.ToViewModel();
        return View(model);
    }
}

src/FixMyHouse/Controllers/ServicesController.cs
using FixMyHouse.Data;
using FixMyHouse.Data.Entities;
using FixMyHouse.Models;
using FixMyHouse.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.CodeAnalysis;

namespace FixMyHouse.Controllers;

public class ServicesController : BaseController
{
    [StringSyntax("Route")]
    private const string ReserveRoute = "[controller]/Reserve/{artisanId:guid}/{serviceId:guid}";

    private readonly ApplicationDbContext _db;

    public ServicesController(ApplicationDbContext db)
    {
        _db = db ?? throw new ArgumentNullException(nameof(db));
    }

    [Authorize]
    [HttpGet("[controller]/EditReservation/{reservationId:guid}")]
    public async Task<IActionResult> EditReservation(Guid reservationId)
    {
        ServiceReservationEntity? entity = await
            _db.ServiceReservations
            .AsNoTracking()
            .SingleOrDefaultAsync(x => x.Id == reservationId);
        if (entity is null) { return NotFound(); }

        return await ReserveInternal(entity.Ref_Artisan, entity.Ref_Service, entity.Id);
    }


    [Authorize]
    [HttpGet(ReserveRoute)]
    public async Task<IActionResult> Reserve(Guid artisanId, Guid serviceId)
    {
        return await ReserveInternal(artisanId, serviceId, existingReservationId: null);
    }

    private async Task<IActionResult> ReserveInternal(Guid artisanId, Guid serviceId, Guid? existingReservationId)
    {
        var artisanService =
            await _db
            .ArtisanServices
            .AsNoTracking()
            .Where(x => x.Ref_Artisan == artisanId && x.Ref_Service == serviceId)
            .Include(x => x.Artisan)
            .Include(x => x.Service)
            .SingleOrDefaultAsync();

        if (artisanService is not { Service: { }, Artisan: { } }) { return NotFound(); }

        ServiceReservationEntity? existingEntity =
            existingReservationId == null ? null :
            await _db.ServiceReservations.AsNoTracking().SingleOrDefaultAsync(x => x.Id == existingReservationId);

        DateTime now = DateTime.Now;

        ReservationViewModel model = new() {
            ReservationId = existingEntity?.Id,
            ArtisanId = artisanService.Artisan.Id,
            ServiceId = artisanService.Service.Id,
            WhenLocal = existingEntity switch {
                null => new DateTime(now.Year, now.Month, now.Day, 12, 0, 0, DateTimeKind.Unspecified).AddDays(Random.Shared.Next(10)), { } => new DateTime(existingEntity.WhenUtc.Ticks, DateTimeKind.Unspecified) + TimeZoneOffset,
            },
            ServiceName = artisanService.Service.Name,
            ArtisanFullName = $"{artisanService.Artisan.FirstName} {artisanService.Artisan.LastName}",

            CustomizationBooleans =
                (existingEntity?.CustomizationBooleans)
                ?? artisanService.CustomizationDefaults.OfType<ServiceCustomizationEntity<bool>>().ToDictionary(static x => x.Id, static x => x.Value),
            CustomizationWholeNumbers =
                (existingEntity?.CustomizationWholeNumbers)
                ?? artisanService.CustomizationDefaults.OfType<ServiceCustomizationEntity<int>>().ToDictionary(static x => x.Id, static x => x.Value),
            CustomizationGuids =
                (existingEntity?.CustomizationGuids)
                ?? artisanService.CustomizationDefaults.OfType<ServiceCustomizationEntity<Guid>>().ToDictionary(static x => x.Id, static x => x.Value),

            CustomizationDefaults = artisanService.CustomizationDefaults.Select(static x => x.ToViewModel()).ToList(),
        };

        return View(nameof(Reserve), model);
    }

    [Authorize]
    public async Task<IActionResult> PostReservation(
        [FromForm] ReservationViewModel model,
        [FromServices] UserManager<IdentityUser> userManager
    )
    {
        if (
            HttpContext.User.Identities.FirstOrDefault(static x => x.IsAuthenticated)
            is not { Name: { } username }
        ) { return Unauthorized(); }

        IdentityUser? user = await userManager.FindByNameAsync(username);
        if (user is null) { return Unauthorized(); }

        var entity =
            await _db
            .ArtisanServices
            .AsNoTracking()
            .Where(x => x.Ref_Artisan == model.ArtisanId && x.Ref_Service == model.ServiceId)
            .SingleOrDefaultAsync();
        if (entity is not { }) { return NotFound(); }

        IReadOnlyList<ServiceCustomizationEntity> customizations = entity.CustomizationDefaults;
        ApplyCustomizations(customizations, model);
        decimal calculatedPrice = customizations.Sum(static x => x.CalculatePrice());

        string userId = user.Id;

        DateTime whenUtc = new DateTimeOffset(model.WhenLocal, TimeZoneOffset).UtcDateTime;
        if (model.ReservationId is { } reservationId)
        {
            ServiceReservationEntity? existing = await _db.ServiceReservations.SingleOrDefaultAsync(x => x.Id == reservationId);
            if (existing is null) { return NotFound(); }
            existing.CustomizationBooleans = model.CustomizationBooleans;
            existing.CustomizationGuids = model.CustomizationGuids;
            existing.CustomizationWholeNumbers = model.CustomizationWholeNumbers;
            existing.WhenUtc = whenUtc;
        }
        else
        {
            _db.ServiceReservations.Add(new() {
                Id = Guid.NewGuid(),
                CalculatedPrice = calculatedPrice,
                Ref_Artisan = entity.Ref_Artisan,
                Ref_Service = entity.Ref_Service,
                Ref_User = userId,
                WhenUtc = whenUtc,
                CustomizationBooleans = model.CustomizationBooleans,
                CustomizationGuids = model.CustomizationGuids,
                CustomizationWholeNumbers = model.CustomizationWholeNumbers,
            });
        }

        await _db.SaveChangesAsync();

        return RedirectToAction(
            controllerName: "Calendar",
            actionName: nameof(CalendarController.Index),
            routeValues: new { year = whenUtc.Year, month = whenUtc.Month }
        );
    }

    [HttpPost]
    public async Task<IActionResult> Calculate([FromForm] ReservationViewModel model)
    {
        var entity =
            await _db
            .ArtisanServices
            .AsNoTracking()
            .Where(x => x.Ref_Artisan == model.ArtisanId && x.Ref_Service == model.ServiceId)
            .Include(x => x.Artisan)
            .Include(x => x.Service)
            .SingleOrDefaultAsync();

        if (entity is not { Service: { }, Artisan: { } }) { return NotFound(); }

        IReadOnlyList<ServiceCustomizationEntity> customizations = entity.CustomizationDefaults;
        ApplyCustomizations(customizations, model);
        decimal calculatedPrice = customizations.Sum(static x => x.CalculatePrice());

        return Json(calculatedPrice);
    }

    private static void ApplyCustomizations(IReadOnlyList<ServiceCustomizationEntity> customizationsTarget, ReservationViewModel modelSource)
    {
        customizationsTarget
            .OfType<ServiceCustomizationEntity<bool>>()
            .ForEach(x => x.Value = modelSource.CustomizationBooleans.GetValueOrNull(x.Id) ?? x.Value);

        customizationsTarget
            .OfType<ServiceCustomizationEntity<int>>()
            .ForEach(x => x.Value = modelSource.CustomizationWholeNumbers.GetValueOrNull(x.Id) ?? x.Value);

        customizationsTarget
            .OfType<ServiceCustomizationEntity<Guid>>()
            .ForEach(x => x.Value = modelSource.CustomizationGuids.GetValueOrNull(x.Id) ?? x.Value);
    }
}

src/FixMyHouse/Views/Artisans/List.cshtml
@model IReadOnlyList<ArtisanViewModel>;

@{
    ViewData["Title"] = "Майстори";
}

<div class="text-center">
    <h1 class="display-4">Списък Майстори</h1>
    @* <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p> *@

    <div style="display: flex; flex-wrap: wrap; gap: 1rem">
        @foreach (var artisan in Model)
        {
            <div class="card" style="width: 18rem" >
                <img 
                    src="/img/@artisan.Picture" 
                    class="card-img-top" 
                    alt="Лична снимка на @artisan.FullName"
                    height="100" width="100"
                    style="height: 18rem;"
                >
                <div class="card-body">
                    <h5 class="card-title">@artisan.FullName</h5>
                    <p class="card-text">@artisan.Bio</p>
                    <a asp-controller="Artisans"
                       asp-action="View"
                       asp-route-id="@artisan.Id"
                       class="btn btn-primary">Виж услугите</a>
                </div>
            </div>
        }
    </div>

</div>

src/FixMyHouse/Views/Artisans/View.cshtml
@model ArtisanViewModel;

@{
    ViewData["Title"] = "Майстор " + Model.FirstName;
}

<div class="text-center">
    <h1 class="display-4">@Model.FullName</h1>
    @* <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p> *@

    <div style="display: flex; flex-wrap: wrap; gap: 1rem">
        @foreach (var service in Model.Services)
        {
            <div class="card" style="width: 18rem;">
                <img src="/img/@service.Picture" class="card-img-top" alt="Снимка на @service.Name"
                     height="100" width="100"
                     style="height: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">@service.Name</h5>
                    <p class="card-text">@service.Description</p>
                    <a asp-controller="Services"
                       asp-action="Reserve"
                       asp-route-artisanId="@service.ArtisanId"
                       asp-route-serviceId="@service.ServiceId"
                       class="btn btn-primary">Заяви услуга</a>
                </div>
            </div>
        }
    </div>

</div>