src/FixMyHouse/Controllers/ArtisansController.cs
using FixMyHouse.Data;
using FixMyHouse.Models;
using FixMyHouse.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FixMyHouse.Controllers;

public sealed class ArtisansController : Controller
{
    private readonly ApplicationDbContext _db;

    public ArtisansController(ApplicationDbContext db)
    {
        _db = db ?? throw new ArgumentNullException(nameof(db));
    }

    public async Task<IActionResult> List()
    {
        var entities = await _db.Artisans.AsNoTracking().ToListAsync();
        var models = entities.Select(static x => x.ToViewModel()).ToList();
        return View(models);
    }

    [Route("[controller]/{id:guid}")]
    public async Task<IActionResult> View(Guid id)
    {
        var entity = await
            _db.Artisans
            .AsNoTracking()
            .Include(x => x.Services!).ThenInclude(x => x.Service)
            .SingleOrDefaultAsync(x => x.Id == id);

        if (entity is null) { return NotFound(); }
        var model = entity.ToViewModel();
        return View(model);
    }
}

src/FixMyHouse/Controllers/CalendarController.cs
using FixMyHouse.Data;
using FixMyHouse.Data.Entities;
using FixMyHouse.Models;
using FixMyHouse.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FixMyHouse.Controllers;

public class CalendarController : BaseController
{
    [Authorize]
    [HttpGet("[controller]/{year:int}-{month:int}")]
    public async Task<IActionResult> Index(
        int year, int month,
        [FromServices] UserManager<IdentityUser> userManager,
        [FromServices] ApplicationDbContext db
    )
    {
        if (
            HttpContext.User.Identities.FirstOrDefault(static x => x.IsAuthenticated)
            is not { Name: { } username }
        ) { return Unauthorized(); }

        IdentityUser? user = await userManager.FindByNameAsync(username);
        if (user is null) { return Unauthorized(); }

        DateOnly firstOfMonth = new(year, month, day: 1);

        DateTime from = new(firstOfMonth.AddDays(-10), time: new(ticks: 0), DateTimeKind.Utc);
        DateTime until = new(firstOfMonth.AddDays(40), time: new(ticks: 0), DateTimeKind.Utc);

        IReadOnlyList<ServiceReservationEntity> entities = await
            db
            .ServiceReservations
            .AsNoTracking()
            .Where(x =>
                x.Ref_User == user.Id
                && x.WhenUtc >= from
                && x.WhenUtc <= until
            )
            .Include(x => x.Service)
            .Include(x => x.Artisan)
            .OrderBy(x => x.WhenUtc)
            .ToListAsync();

        Dictionary<DateOnly, List<CalendarReservationViewModel>> reservations = [];
        foreach (ServiceReservationEntity entity in entities)
        {
            var entryModel = entity.ToCalendarViewModel(TimeZoneOffset);
            reservations.GetOrAdd(entryModel.Date, static () => []).Add(entryModel);
        }

        CalendarViewModel model = new(
            FirstOfMonth: firstOfMonth,
            Reservations: reservations.ToDictionary(x => x.Key, x => x.Value.IReadOnly())
        );

        return View(model);
    }
}

src/FixMyHouse/Views/Shared/_Layout.cshtml
@{
    DateTime now = DateTime.Now;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FixMyHouse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FixMyHouse.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FixMyHouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artisans" asp-action="List">Майстори</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-area=""
                               asp-controller="Calendar"
                               asp-action="Index"
                               asp-route-year="@now.Year"
                               asp-route-month="@now.Month"
                               onclick="">Календар</a>
                        </li>
                        @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FixMyHouse - <a asp-area="" asp-controller="Home" asp-action="Privacy">Политика за поверителност</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    </script>

    <script>
        (() => {
            const offset = new Date().getTimezoneOffset() / (-60);
            document.cookie = `TZOffset=${offset};`
        })();
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>